name: test
desc: test
runbooks:
- name: test
  desc: test
  selectors:
  - type: labelSelector
    selector: k8s-app=calico-kube-controllers
  - type: jsonPathSelector
    selector: '{.apiVersion}=policy/v1'
  - type: jsonPathSelector
    selector: '{.kind}=PodDisruptionBudget'
  - type: jsonPathSelector
    selector: '{.metadata.name}=calico-kube-controllers'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=kube-system'
  doc: test/test.md
